DOMAIN = "goldenergy"

PRICE_ENTITY = "Price"
ELECTRICITY_CONSUMPTION_ENTITY = "Consumption"
GAS_CONSUMPTION_ENTITY = "Gas Consumption"

DEFAULT_MONETARY_ICON = "mdi:currency-eur"
DEFAULT_ELECTRICITY_CONSUMPTION_ICON = "mdi:flash"
DEFAULT_GAS_CONSUMPTION_ICON = "mdi:gas-burner"

UNIT_OF_MEASUREMENT_EURO = "€"
UNIT_OF_MEASUREMENT_ELECTRICITY = "KWh"
UNIT_OF_MEASUREMENT_GAS = "m³"

CONF_CODE = "code"
CONF_PASSWORD = "password"

ATTRIBUTION = "Data provided by Goldenergy"
